server.port: 8080

spring:
  application:
    name: luxmed-interview-app
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/migration/v1
  datasource:
    url: jdbc:postgresql://${app.db.host}/${app.db.name}
    username: ${app.db.username}
    password: ${app.db.password}
    driver-class-name: org.postgresql.Driver

app.db:
  host: localhost:5432
  name: LuxMedDb
  username: luxmed_user
  password: luxmed_pass
