version: '3.9'

services:
  postgres:
    image: postgres:15.2
    container_name: luxmed-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - luxmed_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - luxmed-network

  app:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: luxmed-app
    environment:
      APP_DB_HOST: postgres:5432
      APP_DB_USERNAME: ${POSTGRES_USER}
      APP_DB_PASSWORD: ${POSTGRES_PASSWORD}
      APP_DB_NAME: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - luxmed-network

volumes:
  luxmed_postgres_data:

networks:
  luxmed-network:
    driver: bridge
