CREATE TABLE department
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50)                             NOT NULL,
    company_id BIGINT,
    CONSTRAINT pk_department PRIMARY KEY (id)
);

ALTER TABLE department
    ADD CONSTRAINT FK_DEPARTMENT_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);