CREATE TABLE manager
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(50)                             NOT NULL,
    email        VARCHAR(255),
    phone_number VARCHAR(15),
    CONSTRAINT pk_manager PRIMARY KEY (id)
);