CREATE TABLE project
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(70)                             NOT NULL,
    manager_id BIGINT,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

ALTER TABLE project
    ADD CONSTRAINT uc_project_manager UNIQUE (manager_id);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES manager (id);
