CREATE TABLE team
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(70)                             NOT NULL,
    project_id    BIGINT,
    department_id BIGINT,
    CONSTRAINT pk_team PRIMARY KEY (id)
);

ALTER TABLE team
    ADD CONSTRAINT uc_team_project UNIQUE (project_id);

ALTER TABLE team
    ADD CONSTRAINT FK_TEAM_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE team
    ADD CONSTRAINT FK_TEAM_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);
